### ISSUE TITLE
release: beta version checklist

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-mail#27]
## 1. Global API overview + Prepare docs structure:
- [x] 1.1 Synchronize with new documentation structure inveniosoftware/cookiecutter-invenio-module#56
  - [x] ``docs/requirements.txt`` should exist ([EXAMPLE](https://github.com/inveniosoftware/invenio-celery/blob/master/docs/requirements.txt))
  - [x] Run the cookiecutter repo diffing tool
    - [x] Synchronize all of the 'constant' files (``CONTRIBUTING.rst``, ``.gitignore``, ``babel.ini``, ...)
    - [x] Check all of the 'diffed' files (``README.rst``, ``RELEASE_NOTES.rst``, ...)
    - [x] Manually check all of the remaining files (``setupy.py``, ``.travis.yml``,``tests/conftest.py``,...)
- [x] 1.2 API proof-reading
  - [x] Read and understand API
  - [x] Check existing API methods for feature completeness and correctness.
  - [x] Check if new API needs to be added.
## 2. Local code improvements:
- [x] 2.1 General code improvements 
  - [x] Check code quality all over the module
  - [x] Does QualifiedCode report any errors that can be fixed?
  - [x] Is the test coverage % sufficient across the whole module?
  - [x] Is all core code (API, models) covered with unit test?
  - [x] grep the module for "TODO"/"FIXME". Remove where no longer relevant.
  - [x] Are all strings decorated as translation strings?
- [x] 2.2 Dependencies:
  - [x] Remove unused dependencies in ``setup.py`` and ``requirements-devel.txt``
  - [x] Module should not depend on ``flask_cli`` nor should it instantiate ``FlaskCLI`` extension.
- [x] 2.3 Example app should run.
### 3.1. Write
- [x] 3.1.1 General documentation: 
  - [x] Update feature description in README.rst
  - [x] Document usage / getting started guide inside package docstring ([EXAMPLE](https://github.com/inveniosoftware/invenio-db/blob/master/invenio_db/__init__.py))
  - [x] Make config variables self-documented and imported in the package docs under 'Configuration' section ([EXAMPLE](https://invenio-celery.readthedocs.io/en/latest/usage.html#module-invenio_celery.config) and [EXAMPLE](https://github.com/inveniosoftware/invenio-celery/blob/master/invenio_celery/__init__.py#L25-L35))
  - [x] Add docstring documentation for example app
  - [x] Are all API methods, classes and modules plugged in the documentation as autodoc?
  - [x] Add intersphinx mappings where convenient and make sure they work compiled documentation ([EXAMPLE_REFERENCE](https://github.com/inveniosoftware/invenio-admin/blob/master/invenio_admin/ext.py#L119) and [EXAMPLE_CONFIG](https://github.com/inveniosoftware/invenio-admin/blob/master/docs/conf.py#L332-L337))
  - [x] Are all chapter/section underlines (e.g. ``====``, ``-----``) matching the length of the section/chapter title?
- [x] 3.1.2 Functional documentation:
  - [x] Document all public method docstrings with description and types
    - [x] Methods and functions that accept ``**kwargs`` should document potential arguments and mention if they are passed to another function/method which provides documentation for them.
  - [x] Document signals
### 3.2 Review (read the compiled documentation A-Z)
- [x] Is all imported autodoc documentation being loaded correctly?
- [x] Do all pages and sections contain some text?
- [x] Are all links on the page (API class references, intersphinx links) resolvable?
- [x] Are all text and characters rendered correctly?
  - Non-breaking newlines going outside the page?
  - Strange characters, half-escaped style markers inside docstrings (*, **, ``)
- [x] Docs are compiled and assembled from multiple file/package docstings into single pages - is the assembled block of text easy to read? Unify the compiled text if possible.
- [x] Create a new virtual environment and follow the installation and then getting started guide - does it actually work as described? Add and improve documentation if the description is missing something.
## 4. Miscellaneous: 
- [x] ``MANIFEST.txt``
  - [x] Should be sorted and without comments from auto-updates
  - [x] Should **NOT** contain ``include *.py``
- [x] List of modules in``.editorconfig:known_third_party`` should match 1-to-1 all devel requirements in ``requirements-devel.txt`` (orders of modules should also match) ([.editorconfig](https://github.com/inveniosoftware/invenio-communities/blob/master/.editorconfig#L40) and [requirements-devel.txt](https://github.com/inveniosoftware/invenio-communities/blob/master/requirements-devel.txt))
- [x] ``setup.py``:
  - [x] keywords: check existing keywords for relevance / add new ones
  - [x] entrypoints: check if correct
  - [x] Apply ``'Development Status :: 4 - Beta'``
- [x] Change double bracket "string" to 'string' if you spot it anywhere.

**Comment by krzysztof** [comment]
### 5. Invenio-Mail extras
- [ ] Fix the travis build

**Comment by lnielsen** [comment]
- [ ] Fix inclusion of celery task in documentation

**Comment by krzysztof** [comment]
LGTM

**Comment by lnielsen** [comment]
Closed by 81efd1d58ed534c79fbf1ac3d1674dfdf5b98cfe
